server:
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.101:3306/x_springboot?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456

    jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl